/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.shufange.mavenwebproject.model;

import javax.persistence.*;
 
/**
 * Dbuser generated by hbm2java
 */

@Entity
@Table(name = "book")
public class Book implements java.io.Serializable {
        @Id
	private int isbn;
        
        @Column (name="Name")      
	private String bookName;
        
        @Column (name="ImgNo")      
	private int imageNo;
        
        @ManyToOne
        private User owner;
                
	public Book() {
	}

    public Book(int isbn, String bookName, int imageNo, User owner) {
        this.isbn = isbn;
        this.bookName = bookName;
        this.imageNo = imageNo;
        this.owner = owner;
    }

    public int getIsbn() {
        return isbn;
    }

    public void setIsbn(int isbn) {
        this.isbn = isbn;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public int getImageNo() {
        return imageNo;
    }

    public void setImageNo(int imageNo) {
        this.imageNo = imageNo;
    }

    public User getOwner() {
        return owner;
    }

    public void setOwner(User owner) {
        this.owner = owner;
    }


}